/**
 * MANIFEST FOTO E VIDEO
 * Per sostituire un'illustrazione con una foto: copia il file in /public/media e scrivi qui il percorso in `src`.
 * Esempio:  hero: { src: "/media/rita-hero.jpg", alt: "Rita Dolbakian nel suo studio" }
 * Per i video: `src` = file mp4 in /public/media, `poster` = immagine di copertina.
 * Rapporti consigliati tra parentesi.
 */
export type MediaItem = { src?: string; poster?: string; alt: string; pos?: string }; // pos = object-position, es. "50% 20%"

export const MEDIA: Record<string, MediaItem> = {
  // HOME
  hero: { src: "/media/rita-ritratto-camice.webp", alt: "Rita Dolbakian, ritratto in camice (4:5, verticale)", pos: "50% 25%" },
  "path-agenda": { src: "/media/agenda-cover.webp", alt: "Metodo A.G.E.N.D.A.: copertina con Rita" },
  "path-rd": { src: "/media/rita-massaggio-4.webp", alt: "Mani al lavoro, dettaglio della tecnica (16:11)", pos: "60% 45%" },
  "rita-studio": { src: "/media/rita-lettino.jpg", alt: "Rita Dolbakian seduta sul lettino da massaggio (4:5)", pos: "42% 30%" },
  "riconoscimento": { src: "/media/rita-preoccupata.jpg", alt: "Una professionista del benessere pensierosa davanti alla scrivania (4:3)", pos: "50% 30%" },
  "card-guida": { src: "/media/guida-mockup.webp", alt: "Copertina guida gratuita (4:3)", pos: "50% 32%" },
  "card-call": { src: "/media/rita-videocall.webp", alt: "Rita in call di orientamento (4:3)" , pos: "40% 40%" },
  "card-wm": { src: "/media/wm-cover.webp", alt: "Wellness Mastery: copertina con Rita" },
  "card-rd": { src: "/media/rita-massaggio-1.webp", alt: "Metodo Rita Dolbakian (4:3)", pos: "55% 40%" },
  "guida-copertina": { alt: "Copertina piatta della guida (3:4)" },
  "guida-rita": { src: "/media/rita-tunica.webp", alt: "Rita Dolbakian, autrice della guida", pos: "50% 22%" },
  "guida-pag-1": { alt: "Anteprima pagina interna 1 (4:3)" },
  "guida-pag-2": { alt: "Anteprima pagina interna 2 (4:3)" },
  "guida-pag-3": { alt: "Anteprima pagina interna 3 (4:3)" },
  "prodotto-stories": { src: "/media/prodotto-stories.webp", alt: "Instagram Stories che vendono, il manuale operativo di Rita Dolbakian" },
  "prodotto-calcolatore": { src: "/media/prodotto-calcolatore.webp", alt: "Wellness Profit Calculator, foglio di calcolo per il regime forfettario" },
  "infl-1": { src: "/media/infl-1.webp", alt: "Rita Dolbakian durante un trattamento con una cliente molto presente sui social" },
  "infl-2": { src: "/media/infl-2.webp", alt: "Rita Dolbakian durante un trattamento con una cliente molto presente sui social" },
  "infl-3": { src: "/media/infl-3.webp", alt: "Rita Dolbakian durante un trattamento con una cliente molto presente sui social" },
  "infl-4": { src: "/media/infl-4.webp", alt: "Rita Dolbakian durante un trattamento con una cliente molto presente sui social" },
  "guida-mockup": { src: "/media/guida-mockup.webp", alt: "La guida gratuita «Il Sistema Clienti per Operatori del Benessere» di Rita Dolbakian" },
  // PERCORSI
  "agenda-hero": { src: "/media/rita-conversazione.webp", alt: "Rita in affiancamento (4:3)" , pos: "60% 40%" },
  "wm-video": { alt: "Rita presenta Wellness Mastery (video 16:10)" },
  "rd-hands": { alt: "Mani al lavoro, dettaglio tecnica (4:5)" },
  "rd-online": { src: "/media/lezione-due.webp", alt: "Anteprima lezione online (video 16:9)"  },
  "rd-aula": { src: "/media/aula-grande.webp", alt: "Formazione in presenza, aula (16:9)"  },
  // PERCORSI (hub + pagine)
  "percorsi-agenda": { src: "/media/agenda-cover.webp", alt: "Metodo A.G.E.N.D.A.: copertina con Rita" },
  "percorsi-wm": { src: "/media/wm-cover.webp", alt: "Wellness Mastery: copertina con Rita" },
  "percorsi-rd": { src: "/media/rita-massaggio-5.webp", alt: "Card Metodo Rita Dolbakian (4:3)", pos: "70% 45%" },
  "agenda-prima": { src: "/media/agenda-prima.webp", alt: "Prima: pochi clienti, agenda disordinata, stress" },
  "agenda-dopo": { src: "/media/agenda-dopo.webp", alt: "Dopo: agenda piena, prezzi più alti, più serenità" },
  "wm-hero": { src: "/media/rita-tablet.webp", alt: "Rita in studio con tablet, Wellness Mastery (4:5)" , pos: "42% 40%" },
  "wm-fase-1": { alt: "Fase 1, fondamenta (4:3)" },
  "wm-fase-2": { src: "/media/rita-social-2.webp", alt: "Fase 2, visibilità (4:3)", pos: "50% 60%" },
  "wm-fase-3": { alt: "Fase 3, vendita e sistema (4:3)" },
  "rd-hero": { src: "/media/rita-massaggio-2.webp", alt: "Rita mentre insegna una tecnica (4:5)", pos: "50% 40%" },
  "rd-livello-1": { src: "/media/rita-massaggio-4.webp", alt: "Livello 1, fondamenta del tocco (4:3)", pos: "60% 45%" },
  "rd-livello-2": { src: "/media/rita-massaggio-1.webp", alt: "Livello 2, tecnica e precisione (4:3)", pos: "55% 40%" },
  "rd-livello-3": { src: "/media/rita-massaggio-5.webp", alt: "Livello 3, perfezionamento (4:3)", pos: "70% 45%" },
  "rd-docente": { src: "/media/rita-massaggio-3.webp", alt: "Rita come insegnante (4:5)", pos: "70% 40%" },
  // FORMAZIONE CERTIFICATA
  "cert-hero": { src: "/media/lezione-gruppo.webp", alt: "Rita in aula con un gruppo piccolo (16:10)"  },
  "cert-livello-1": { src: "/media/rita-massaggio-4.webp", alt: "Livello 1 (4:3)", pos: "60% 45%" },
  "cert-livello-2": { src: "/media/rita-massaggio-1.webp", alt: "Livello 2 (4:3)", pos: "55% 40%" },
  "cert-livello-3": { src: "/media/rita-massaggio-5.webp", alt: "Livello 3 (4:3)", pos: "70% 45%" },
  "cert-attestato": { alt: "L'attestato reale (4:3)" },
  // CORSI (catalogo)
  "corso-guida": { src: "/media/guida-mockup.webp", alt: "Copertina corso: guida gratuita (4:3)", pos: "50% 32%" },
  "corso-agenda": { src: "/media/agenda-cover.webp", alt: "Metodo A.G.E.N.D.A.: copertina con Rita" },
  "corso-wm": { src: "/media/wm-cover.webp", alt: "Wellness Mastery: copertina con Rita" },
  "corso-rd-online": { src: "/media/rita-massaggio-3.webp", alt: "Copertina corso: Metodo RD online (4:3)", pos: "70% 40%" },
  "corso-rd-presenza": { src: "/media/aula-grande.webp", alt: "Copertina corso: Metodo RD in presenza (4:3)"  },
  // ALTRE PAGINE
  "call-hero": { src: "/media/rita-videocall.webp", alt: "Rita sorride alla videochiamata (4:5)" , pos: "28% 40%" },
  "contatti-hero": { src: "/media/rita-porta.webp", alt: "Rita, ritratto per la pagina contatti (4:5)" , pos: "50% 25%" },
  "risultati-hero": { alt: "Rita con una allieva (autorizzata) (16:9)" },
  "area-privata": { src: "/media/rita-divano.webp", alt: "Studio accogliente, area privata (16:9)" , pos: "30% 40%" },
  // Foto in testata delle pagine (due colonne)
  "agenda-top": { src: "/media/agenda-cover.webp", alt: "Metodo A.G.E.N.D.A.: copertina con Rita" },
  "wm-top": { src: "/media/wm-cover.webp", alt: "Wellness Mastery: copertina con Rita" },
  "rd-top": { src: "/media/rita-massaggio-1.webp", alt: "Rita mostra una tecnica a un piccolo gruppo (immagine illustrativa)", pos: "55% 40%" },
  "cert-top": { src: "/media/rita-massaggio-1.webp", alt: "Una lezione in aula (immagine illustrativa)", pos: "55% 40%" },
  "percorsi-top": { src: "/media/rita-laptop.webp", alt: "Rita al computer nel suo studio", pos: "52% 35%" },
  "corsi-top": { src: "/media/rita-oli.webp", alt: "Rita nel suo studio, tra gli oli", pos: "50% 30%" },
  "garanzia-testo": { src: "/media/garanzia-testo.webp", alt: "Rita Dolbakian con la mano sul cuore: Soddisfatti o rimborsati. Per tutto il percorso. Il rischio è mio.", pos: "50% 25%" },
  "wm-garanzia": { src: "/media/wm-garanzia.webp", alt: "Rita Dolbakian con la mano sul cuore: il rischio è mio", pos: "50% 30%" },
  // CHI SONO: storia e galleria (foto reali)
  "story-bar": { src: "/media/rita-bar.webp", alt: "Rita dietro il bancone di un bar, quando lavorava come barista", pos: "50% 45%" },
  "story-bar-2": { src: "/media/rita-bar-2.webp", alt: "Rita dietro il bancone con un cocktail e un vassoio di dolci", pos: "50% 30%" },
  "story-frustrazione": { src: "/media/rita-preoccupata.jpg", alt: "Rita pensierosa e frustrata davanti alla scrivania", pos: "50% 30%" },
  "story-mani": { src: "/media/rita-massaggio-2.webp", alt: "Rita durante un massaggio sulla schiena", pos: "50% 40%" },
  "story-social": { src: "/media/rita-social.webp", alt: "Rita registra un contenuto all'aperto con il telefono su treppiede", pos: "50% 62%" },
  "story-oggi": { src: "/media/rita-tunica.webp", alt: "Rita Dolbakian oggi, in camice, braccia incrociate", pos: "50% 25%" },
  "gallery-1": { src: "/media/rita-massaggio-1.webp", alt: "Rita durante un massaggio alla schiena", pos: "55% 40%" },
  "gallery-2": { src: "/media/rita-massaggio-4.webp", alt: "Rita durante un massaggio ai piedi", pos: "60% 45%" },
  "gallery-3": { src: "/media/rita-massaggio-3.webp", alt: "Rita durante un massaggio al braccio", pos: "70% 40%" },
  "gallery-4": { src: "/media/rita-social-2.webp", alt: "Rita registra contenuti all'aperto", pos: "50% 62%" },
  "gallery-5": { src: "/media/rita-social-3.webp", alt: "Rita lavora al telefono sotto un albero", pos: "50% 62%" },
  "gallery-6": { src: "/media/rita-massaggio-5.webp", alt: "Rita durante un massaggio alle gambe", pos: "70% 45%" },
  // CHI SONO
  "about-portrait": { src: "/media/rita-lettino.jpg", alt: "Rita Dolbakian seduta sul lettino da massaggio (4:5)", pos: "42% 30%" },
  "about-video": { alt: "Video di presentazione (16:10)" },
  "about-allieve": { alt: "Rita con le allieve (4:5)" },
  // BLOG: copertine degli articoli (4:3). Per la testata dell'articolo si usa la stessa immagine (16:9 ritagliata).
  "blog-come-trovare-clienti-massaggiatrice": { src: "/media/blog-come-trovare-clienti-massaggiatrice.webp", alt: "Copertina: come trovare clienti massaggiatrice" },
  "blog-agenda-massaggiatrice-mesi-vuoti": { src: "/media/blog-agenda-massaggiatrice-mesi-vuoti.webp", alt: "Copertina: agenda massaggiatrice mesi vuoti" },
  "blog-quanto-far-pagare-un-massaggio": { src: "/media/blog-quanto-far-pagare-un-massaggio.webp", alt: "Copertina: quanto far pagare un massaggio" },
  "blog-fidelizzare-clienti-massaggi": { src: "/media/blog-fidelizzare-clienti-massaggi.webp", alt: "Copertina: fidelizzare clienti massaggi" },
  "blog-instagram-per-massaggiatrici": { src: "/media/blog-instagram-per-massaggiatrici.webp", alt: "Copertina: instagram per massaggiatrici" },
  "blog-come-rispondere-quanto-costa": { src: "/media/blog-come-rispondere-quanto-costa.webp", alt: "Copertina: come rispondere quanto costa" },
  "blog-google-business-profile-massaggiatori": { src: "/media/blog-google-business-profile-massaggiatori.webp", alt: "Copertina: google business profile massaggiatori" },
  "blog-come-scegliere-un-corso-di-massaggio": { src: "/media/blog-come-scegliere-un-corso-di-massaggio.webp", alt: "Copertina: come scegliere un corso di massaggio" },
  "blog-corso-massaggio-online-funziona": { src: "/media/blog-corso-massaggio-online-funziona.webp", alt: "Copertina: corso massaggio online funziona" },
  "blog-imparare-a-massaggiare-da-zero": { src: "/media/blog-imparare-a-massaggiare-da-zero.webp", alt: "Copertina: imparare a massaggiare da zero" },
  "blog-errori-comuni-chi-inizia-a-massaggiare": { src: "/media/blog-errori-comuni-chi-inizia-a-massaggiare.webp", alt: "Copertina: errori comuni chi inizia a massaggiare" },
  "blog-come-diventare-massaggiatrice-professionista": { src: "/media/blog-come-diventare-massaggiatrice-professionista.webp", alt: "Copertina: come diventare massaggiatrice professionista" },
  "blog-chi-puo-fare-massaggi-in-italia": { src: "/media/blog-chi-puo-fare-massaggi-in-italia.webp", alt: "Copertina: chi puo fare massaggi in italia" },
  "blog-attestato-massaggio-valido-italia": { src: "/media/blog-attestato-massaggio-valido-italia.webp", alt: "Copertina: attestato massaggio valido italia" },
  "blog-partita-iva-massaggiatore": { src: "/media/blog-partita-iva-massaggiatore.webp", alt: "Copertina: partita iva massaggiatore" },
  "blog-quanto-guadagna-una-massaggiatrice": { src: "/media/blog-quanto-guadagna-una-massaggiatrice.webp", alt: "Copertina: quanto guadagna una massaggiatrice" },
  "blog-massaggiatrice-domicilio-o-studio": { src: "/media/blog-massaggiatrice-domicilio-o-studio.webp", alt: "Copertina: massaggiatrice domicilio o studio" },
  "blog-come-aprire-un-centro-massaggi": { src: "/media/blog-come-aprire-un-centro-massaggi.webp", alt: "Copertina: come aprire un centro massaggi" },
  "blog-gestire-disdette-clienti": { src: "/media/blog-gestire-disdette-clienti.webp", alt: "Copertina: gestire disdette clienti" },
  "blog-whatsapp-business-massaggiatori": { src: "/media/blog-whatsapp-business-massaggiatori.webp", alt: "Copertina: whatsapp business massaggiatori" },
  author: { src: "/media/rita-ritratto-camice.webp", alt: "Rita Dolbakian", pos: "50% 22%" },
  "agenda-cover": { src: "/media/agenda-cover.webp", alt: "Metodo A.G.E.N.D.A.: copertina con Rita" },
  "wm-cover": { src: "/media/wm-cover.webp", alt: "Wellness Mastery: copertina con Rita" },
  "chi-sono-bg": { src: "/media/rita-bn.webp", alt: "Rita Dolbakian, ritratto in bianco e nero", pos: "0% 30%" },
};
